### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by garlen-javier** [jaysavsani07/Google-Cast-Demo#2]
I tried to follow this tutorial, infact I even download this repo and run it but I still get black screen on the receiver device. May I ask if this still working on latest IOS?

**Comment by jaysavsani07** [comment]
Hi @garlen-javier I haven't tested it with the latest iOS device as of now, but I'm using very similar setup in one of my private project for casting where I've upgraded pods with latest version and everything works smoothly. I've separated this code from that private repo only. so If that's working then it should work with the updated dependencies. Hope it helps!!

**Comment by garlen-javier** [comment]
@jaysavsani07 thanks for the fast reply, probably I need to use the app id given from the Cast Developer Console rather than the default constant value. I tried changing it and it's not black screen anymore but still can't play it, I'll try to investigate it again.

**Comment by jaysavsani07** [comment]
@garlen-javier iOS 14 has updates for providing permission differently then prior iOS version. Please check that if you're getting any permission pop-up from iPhone devices.
Let me know if I can help anywhere.

**Comment by garlen-javier** [comment]
Thanks, may I know what should I put in App Launch URI? Can't even find good answers around the web.

![Screen Shot 2021-03-15 at 4 31 20 PM](https://user-images.githubusercontent.com/71249192/111124916-01713e80-85ac-11eb-8f90-eca87ba868ad.png)

**Comment by jaysavsani07** [comment]
@garlen-javier I don't have any experience on making receiver app for Chrome cast. I only made sender app.

**Comment by garlen-javier** [comment]
Ok thanks I think I slowly understand the flow.

**Comment by jaysavsani07** [comment]
@garlen-javier closing this issue. Reopen if you find anything else.
